name: ASR
main: iJoshuaHD\iMCPE\ASR\Loader
version: 2.0.2
api: [2.0.0,3.0.0,3.0.0=ALPHA4,3.0.0-ALPHA5]
load: STARTUP
author: iJoshuaHD
description: Restarts your server at given interval.
website: https://github.com/iJoshuaHD/ASR
commands:
 asr:
  description: "Set ASR Time"
  permission: asr.command.asr
 restart:
  description: "Check ASR Status"
  permission: asr.command.restart
permissions:
 asr.command.asr:
  description: "Usage: /asr <value>"
  default: op
 asr.command.restart:
  description: "Usage: /restart"
  default: true
